name: BossWars
main: Boss.Boss
description: It`s minigame by _MediaNik_ (Idea by http://forum.minecorp.ru/viewtopic.php?pid=57447)
version: 0.1.0 Beta

commands:
  bs:
    usage: /bs
  bsetlobby:
    usage: /bsetlobby <world> (x,y,z will be find automatical)
  breload:
    usage: /breload
  bcreate:
    usage: /bcreate <name>
  bsave:
    usage: /bsave
  bpos1:
    usage: /bpos1
  bpos2:
    usage: /bpos2
  bsspawn:
    usage: /bsspawn <world> (x,y,z will be find automatical)
  bsspawnb:
    usage: /bsspawnb <world> (x,y,z will be find automatical)